export const dimensionDescriptions = [
  { id: 'giniIndex',       description: 'Gini index measures the extent to which the distribution of income (or, in some cases, consumption expenditure) among individuals or households within an economy deviates from a perfectly equal distribution. A Lorenz curve plots the cumulative percentages of total income received against the cumulative number of recipients, starting with the poorest individual or household. The Gini index measures the area between the Lorenz curve and a hypothetical line of absolute equality, expressed as a percentage of the maximum area under the line. Thus a Gini index of 0 represents perfect equality, while an index of 100 implies perfect inequality.' },
  { id: 'unemployment',    description: 'Percentage of total population, age group above 15, that has been registered as unemployed during the given year.' },
  { id: 'corruption',      description: 'This index ranks countries/territories based on how corrupt their public sector is perceived to be. The Corruption Perception Index by TI is the most widely used indicator of corruption worldwide. It is scaled on a range of 0 to 100, where 0 is highly corrupt and 100 is very clean.' },
  { id: 'lifeExpectancy',  description: 'The number of years a newborn infant would live if the current mortality rates at different ages were to stay the same throughout its life.' },
  { id: 'happiness',       description: 'This is the national average response to the question of life evaluations asking the following "Please imagine a ladder, with steps numbered from 0 at the bottom to 10 at the top. The top of the ladder represents the best possible life for you and the bottom of the ladder represents the worst possible life for you. On which step of the ladder would you say you personally feel you stand at this time?" This measure is also referred to as Cantril life ladder. Gapminder has converted the scale of this indicator from 0 to 100 to easly communicate it in terms of percentage.' },
  { id: 'suicideRate',     description: 'Mortality due to self-inflicted injury, per 100 000 standard population, age adjusted. This rate is calculated as if all countries had the same age composition of the population.' },
  { id: 'literacyRate',    description: 'Adult literacy rate is the percentage of people ages 15 and above who can, with understanding, read and write a short, simple statement on their everyday life.' },
  { id: 'inflation',       description: 'Inflation as measured by the annual growth rate of the GDP implicit deflator shows the rate of price change in the economy as a whole. The GDP implicit deflator is the ratio of GDP in current local currency to GDP in constant local currency.' },
  { id: 'democracyIndex',  description: "Overall polity score from the Polity5 dataset, calculated by subtracting an autocracy score from a democracy score. It is a summary measure of a country's democratic and free nature. -10 is the lowest value, 10 the highest." },
]
